# Generated by Django 5.2 on 2025-05-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('for_four', 'For_four')], max_length=10),
        ),
    ]
